name: E2E Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  eun-e2e-tests:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Run web app
      run: dotnet run --project src/CookieSample/CookieSample.csproj &

    - name: Run E2E Tests
      run: dotnet test src/CookieSample.E2ETests/CookieSample.E2ETests.csproj

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs
        path: src/CookieSample.E2ETests/bin/Release/net8.0/logs
