name: E2E Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  eun-e2e-tests:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Build solution
      run: dotnet build -c Release

    - name: Run the web app and E2E tests
      run: |
        dotnet run --project src/CookieSample/CookieSample.csproj --no-build &
        sleep 3
        dotnet test src/CookieSample.E2ETests/CookieSample.E2ETests.csproj

    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: logs
        path: src/CookieSample.E2ETests/bin/Debug/net9.0/logs
