name: E2E Test

on: [push]

jobs:
  eun-e2e-tests:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - name: Build and Run E2E Tests
      run: .\build.ps1 --target Run-E2E-Tests
      shell: pwsh

    - name: Upload logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: logs
        path: src/CookieSample.E2ETests/bin/Release/net6.0/logs
