name: E2E Test

on: [push]

jobs:
  eun-e2e-tests:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Build and Run E2E Tests On Linux
      run: |
        .\build.ps1 --target Run-E2E-Tests --removeContainers false
      shell: pwsh

    - name: Upload logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: logs
        path: src/CookieSample.E2ETests/bin/Release/net6.0/logs
